from .client import ClientSerializer
from .aptitude import AptitudeSerializer
from .etat_affaire import EtatSerializer
from .pointage import PointageSerializer
from .fournisseur import FournisseurSerializer
from .facture import FactureSerializer
from .fourniture import FournitureSerializer
from .type_fourniture import TypeFournitureSerializer
from .achat_fourniture import AchatFournitureSerializer
from .user import UserSerializer
from .statut import StatutSerializer
