from .statut import Statut
from .client import Client
from api.salarie.models import Salarie
from .aptitude import Aptitude
from .etat_affaire import Etat
from .facture import Facture
from .fournisseur import Fournisseur
from .fourniture import Fourniture
from .type_fourniture import TypeFourniture
from .achat_fourniture import AchatFourniture
from api.machine.models import Machine
from api.affectation_etape_zone.models import AffectationAjustage
