# Generated by Django 4.1.4 on 2022-12-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="date_rendu",
            field=models.DateField(blank=True, null=True, verbose_name="date rendu"),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="etat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.etat",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="statut",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.statut",
            ),
        ),
    ]
