# Generated by Django 4.1.6 on 2023-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
