# Generated by Django 4.1.6 on 2023-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_note_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=10000,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
