# Generated by Django 4.1.6 on 2023-09-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_etape_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="plan",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="etape",
            name="ref_doc",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="etape",
            name="rep",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
    ]
