# Generated by Django 4.1.4 on 2023-01-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_fiche_etape"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupeMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_groupe_machine", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_machine", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("fonctionnelle", models.BooleanField(default=True)),
                (
                    "groupe_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.groupemachine",
                    ),
                ),
            ],
        ),
    ]
