# Generated by Django 4.1.6 on 2023-09-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_etape_plan_alter_etape_ref_doc_alter_etape_rep"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affectationajustage",
            options={
                "verbose_name": "Affectation Ajustage",
                "verbose_name_plural": "Affectations Ajustage",
            },
        ),
        migrations.AlterModelOptions(
            name="affectationmachine",
            options={
                "verbose_name": "Affectation Machine",
                "verbose_name_plural": "Affectations Machine",
            },
        ),
        migrations.AddField(
            model_name="affectationajustage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
