# Generated by Django 4.1.4 on 2023-01-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_zone_remove_etape_observation_etape_machine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarie",
            name="aptitude",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.aptitude",
            ),
        ),
        migrations.AlterField(
            model_name="salarie",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.zone",
            ),
        ),
    ]
