# Generated by Django 4.1.4 on 2023-01-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_salarie_aptitude_alter_salarie_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semaine_affectation",
                    models.DateField(
                        verbose_name="Semaine d'affectation de la fiche"
                    ),
                ),
                (
                    "fiche",
                    models.OneToOneField(
                        default=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.fiche",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.zone",
                    ),
                ),
            ],
        ),
    ]
