# Generated by Django 4.1.6 on 2023-10-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_affectationajustage_previous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="description",
            field=models.TextField(
                default="", max_length=10000, verbose_name="Description"
            ),
        ),
    ]
