# Generated by Django 4.1.4 on 2023-01-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_affectation"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="fiches",
            field=models.ManyToManyField(
                through="api.Affectation", to="api.fiche"
            ),
        ),
    ]
