# Generated by Django 4.1.6 on 2023-10-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_etape_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapemodele",
            name="description",
            field=models.TextField(
                default="", max_length=10000, verbose_name="Description"
            ),
        ),
    ]
