# Generated by Django 4.1.6 on 2023-02-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_fiche_groupe_machine_alter_affaire_charge_affaire_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Affectation",
            new_name="AffectationAjustage",
        ),
    ]
