# Generated by Django 4.1.6 on 2023-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_etape_quantite_alter_etapemodele_quantite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="temps",
            field=models.IntegerField(default=1, verbose_name="Temps nécessaire"),
        ),
        migrations.AlterField(
            model_name="etapemodele",
            name="temps",
            field=models.IntegerField(default=1, verbose_name="Temps nécessaire"),
        ),
    ]
