# Generated by Django 4.1.6 on 2023-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_affectation_affectationajustage"),
    ]

    operations = [
        migrations.AddField(
            model_name="affaire",
            name="num_affaire",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
