# Generated by Django 4.1.6 on 2023-10-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_etape_temps_alter_etapemodele_temps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationajustage",
            name="previous",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next",
                to="api.affectationajustage",
            ),
        ),
        migrations.AlterField(
            model_name="affectationmachine",
            name="previous",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next",
                to="api.affectationmachine",
            ),
        ),
    ]
