# Generated by Django 4.1.6 on 2023-02-10 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_affaire_num_affaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="num_affaire",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
