# Generated by Django 4.1.6 on 2023-02-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_affaire_num_affaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="fiche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapes",
                to="api.fiche",
            ),
        ),
        migrations.AlterField(
            model_name="etape",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.machine",
            ),
        ),
    ]
