# Generated by Django 4.1.6 on 2023-10-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_affectationajustage_previous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationajustage",
            name="etape",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.etape",
            ),
        ),
        migrations.AlterField(
            model_name="affectationmachine",
            name="etape",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.etape",
            ),
        ),
    ]
