# Generated by Django 4.1.6 on 2023-02-11 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_etape_fiche_alter_etape_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="num_affaire",
            field=models.IntegerField(
                null=True,
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
