# Generated by Django 4.1.6 on 2023-10-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_affectationajustage_etape_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationajustage",
            name="etape",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.etape"
            ),
        ),
        migrations.AlterField(
            model_name="affectationmachine",
            name="etape",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.etape"
            ),
        ),
    ]
