# Generated by Django 4.1.6 on 2023-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_affaire_num_affaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiche",
            name="titre",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="fiche",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
