# Generated by Django 4.1.6 on 2023-11-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_affectationajustage_etape_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="charge_affaire",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                verbose_name="nom du chargé d'affaire",
            ),
        ),
        migrations.AlterField(
            model_name="affectationajustage",
            name="etape",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affectationajustage",
                to="api.etape",
            ),
        ),
        migrations.AlterField(
            model_name="affectationmachine",
            name="etape",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affectationmachine",
                to="api.etape",
            ),
        ),
    ]
