# Generated by Django 4.1.6 on 2023-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_fiche_titre_alter_fiche_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affaire",
            name="raison",
        ),
        migrations.AlterField(
            model_name="affaire",
            name="description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
