# Generated by Django 4.1.6 on 2023-03-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_affaire_raison_alter_affaire_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affaire",
            name="devis",
        ),
    ]
