# Generated by Django 4.1.6 on 2024-01-05 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_affaire_charge_affaire_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etape",
            options={"ordering": ["num_etape", "pk"]},
        ),
        migrations.AddField(
            model_name="note",
            name="vue_par",
            field=models.ManyToManyField(
                blank=True, related_name="notes_vues", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="groupe_machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="api.groupemachine",
            ),
        ),
    ]
