# Generated by Django 4.1.6 on 2023-03-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_fiche_groupe_machine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etape",
            name="matiere",
        ),
        migrations.AddField(
            model_name="etape",
            name="plan",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="etape",
            name="rep",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
