# Generated by Django 4.1.6 on 2023-03-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_etape_matiere_etape_plan_etape_rep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affectationajustage",
            name="fiche",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="fiches",
        ),
        migrations.AddField(
            model_name="affectationajustage",
            name="etape",
            field=models.OneToOneField(
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.etape",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="etapes",
            field=models.ManyToManyField(
                through="api.AffectationAjustage", to="api.etape"
            ),
        ),
        migrations.AlterField(
            model_name="affectationajustage",
            name="semaine_affectation",
            field=models.DateField(
                verbose_name="Semaine d'affectation de l'étape"
            ),
        ),
    ]
