# Generated by Django 4.1.6 on 2023-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_merge_20230323_1703"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="est_active",
            field=models.BooleanField(default=True),
        ),
    ]
