# Generated by Django 4.1.6 on 2023-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_machine_est_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheModele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_modele", models.CharField(max_length=255)),
                ("description_modele", models.TextField(blank=True, null=True)),
                (
                    "date_creation_modele",
                    models.DateField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                ("titre", models.CharField(default="", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("ref_doc", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fourniture",
                    models.BooleanField(
                        default=False, verbose_name="Fournitures arrivées"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche modèle",
                "verbose_name_plural": "Fiches modèle",
            },
        ),
    ]
