# Generated by Django 4.1.6 on 2023-04-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_fichemodele_ref_doc"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapeModele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_etape", models.IntegerField(verbose_name="N°Étape")),
                ("quantite", models.IntegerField(default=0, verbose_name="Quantité")),
                (
                    "temps",
                    models.IntegerField(default=0, verbose_name="Temps nécessaire"),
                ),
                ("plan", models.CharField(blank=True, max_length=2000, null=True)),
                ("rep", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "terminee",
                    models.BooleanField(default=False, verbose_name="Terminée ?"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "fiche_modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etapes_modele",
                        to="api.fichemodele",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.machine"
                    ),
                ),
            ],
        ),
    ]
