# Generated by Django 4.1.6 on 2023-04-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_etapemodele"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichemodele",
            old_name="date_creation_modele",
            new_name="date_creation",
        ),
        migrations.RemoveField(
            model_name="fichemodele",
            name="description_modele",
        ),
        migrations.RemoveField(
            model_name="fichemodele",
            name="nom_modele",
        ),
    ]
