# Generated by Django 4.1.6 on 2023-05-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_etapemodele_fiche_modele"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationajustage",
            name="etape",
            field=models.OneToOneField(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.etape",
            ),
        ),
        migrations.AlterField(
            model_name="affectationajustage",
            name="zone",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.zone",
            ),
        ),
        migrations.CreateModel(
            name="AffectationMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semaine_affectation",
                    models.DateField(verbose_name="Semaine d'affectation de l'étape"),
                ),
                (
                    "etape",
                    models.OneToOneField(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.etape",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.machine",
                    ),
                ),
            ],
        ),
    ]
