# Generated by Django 4.1.6 on 2023-07-05 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_affectationmachine_salarie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affaire",
            name="etat",
        ),
        migrations.AlterField(
            model_name="affaire",
            name="client",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nom du client"
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="date_cloture",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="date de clôture de l'affaire (terminée)",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="date_creation",
            field=models.DateField(
                auto_now_add=True,
                verbose_name="date de création de l'affaire (ajout à notre bd)",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="date_rendu",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="date à laquelle l'affaire doit être terminée",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Description de l'affaire",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="montant de l'affaire",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="num_affaire",
            field=models.IntegerField(
                null=True,
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Numéro d'affaire correspondant à l'affaire dans la base de données de SGM",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="observation",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Observation faite sur l'affaire",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="ref_doc",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="référence vers un document stocké sur serveur local",
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[("SOO", "Sous offre")],
                max_length=200,
                null=True,
                verbose_name="statut de l'affaire",
            ),
        ),
    ]
