# Generated by Django 4.1.6 on 2023-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_remove_affaire_etat_alter_affaire_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[("S00", "Sous offre"), ("ENC", "En cours")],
                max_length=200,
                null=True,
                verbose_name="statut de l'affaire",
            ),
        ),
    ]
