# Generated by Django 4.1.6 on 2023-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_affaire_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S00", "Sous offre"),
                    ("A00", "ABANDON"),
                    ("EHA", "ACHATS"),
                    ("EAA", "ATTENTE ACCORD COMMANDE"),
                    ("EAC", "ATTENTE CLIENT"),
                    ("P00", "AFFAIRE PERDUE"),
                    ("T00", "Affaire Terminée"),
                    ("E00", "Affaire en cours"),
                    ("ECC", "CHIFFRAGE POUR REPARATION"),
                    ("INT", "COMMANDE INTERNE"),
                    ("ECA", "ENCOURS CHIFFRAGE ACHAT"),
                    ("ED", "EXPERTISE ATELIER"),
                    ("D00", "Etat de Devis"),
                    ("G00", "NON REFACTURE"),
                    ("SV0", "SOLDES VERIFIES"),
                    ("EST", "ST / ACHATS"),
                    ("ECH", "chantier"),
                ],
                max_length=200,
                null=True,
                verbose_name="statut de l'affaire",
            ),
        ),
    ]
