# Generated by Django 4.1.6 on 2023-07-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_affaire_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="affaire",
            name="hash_sgm_bd",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="hash de l'affaire dans la base de données SGM",
            ),
        ),
    ]
