# Generated by Django 4.1.6 on 2023-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="date_creation",
            field=models.DateField(auto_now=True),
        ),
    ]
