# Generated by Django 4.1.6 on 2023-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_note_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="date_creation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
