# Generated by Django 4.1.6 on 2023-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_alter_note_date_creation"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupeMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_groupe",
                    models.CharField(
                        max_length=300, verbose_name="Nom du groupe machine"
                    ),
                ),
                (
                    "prix_theorique",
                    models.IntegerField(
                        default=0, verbose_name="Prix théorique / heure"
                    ),
                ),
            ],
        ),
    ]
