# Generated by Django 4.1.6 on 2023-08-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_groupemachine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etape",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="etapemodele",
            name="machine",
        ),
        migrations.AddField(
            model_name="etape",
            name="groupe_machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.groupemachine",
            ),
        ),
        migrations.AddField(
            model_name="etapemodele",
            name="groupe_machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.groupemachine",
            ),
        ),
    ]
