# Generated by Django 4.1.6 on 2023-08-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0041_remove_etape_machine_remove_etapemodele_machine_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="groupe_machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.groupemachine",
            ),
        ),
    ]
