# Generated by Django 4.1.6 on 2023-08-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_machine_groupe_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="groupe_machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.groupemachine",
            ),
        ),
    ]
