# Generated by Django 4.1.6 on 2023-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_machine_groupe_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="affaire",
            name="validation_ingenieur",
            field=models.BooleanField(
                default=False, verbose_name="Validation de l'ingénieur"
            ),
        ),
    ]
