apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sgm-staging
type: Opaque
data:
  POSTGRES_NAME:   XXXXXBASE54=
  POSTGRES_USER: XXXXXBASE54=
  POSTGRES_PASSWORD:  XXXXXBASE54=
  POSTGRES_HOST:    XXXXXBASE54=
