name: Component / Deploy

on:
  # Allows you to include this workflow in other workflows
  workflow_call:
    inputs:
      affected_projects:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:

  deploy:
    name: Deploy - ${{ matrix.project }}
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}

    strategy:
      matrix:
        project: ${{ fromJson(inputs.affected_projects) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.project }}-build
          path: dist/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug
        run: |
          tree

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./infra/docker/${{ matrix.project }}.Dockerfile
          push: true
          tags: aimerisson/sgm-${{ matrix.project }}-${{ github.ref_name == 'main' && 'prod' || 'staging' }}:${{ steps.commit.outputs.short }}
