name: affected

on:

  # Allows you to include this workflow in other workflows
  workflow_call:
    outputs:
      affected_projects:
        description: 'Affected projects'
        value: ${{ jobs.affected.outputs.affected_projects }}
      nx_base:
        description: 'Base SHA for Nx'
        value: ${{ jobs.affected.outputs.nx_base }}
      nx_head:
        description: 'Head SHA for Nx'
        value: ${{ jobs.affected.outputs.nx_head }}

jobs:

  affected:
    name: Get affected projects
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: nrwl/nx-set-shas@v3
        id: set-shas
        with:
          main-branch-name: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Get projects to build
        id: get-projects-to-build
        run: |
          echo "affected_projects=$(pnpm nx show projects --affected --json -p 'apps/*' | jq -c)" >> $GITHUB_OUTPUT

    outputs:
      affected_projects: ${{ steps.get-projects-to-build.outputs.affected_projects }}
      nx_base: ${{ steps.set-shas.outputs.base }}
      nx_head: ${{ steps.set-shas.outputs.head }}
