name: CI

on:

  push:
    branches:
      - dev

  pull_request:

  # Allows you to include this workflow in other workflows
  workflow_call:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}"

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm i

      - name: (Debug) Show affected
        run: pnpm nx show projects --affected

      - name: Lint
        run: pnpm nx affected -t lint

      - name: Tests
        run: pnpm nx affected -t test

      - name: Build
        run: pnpm nx affected -t build
