name: build

on:

  push:
    branches:
      - dev

  pull_request:

  # Allows you to include this workflow in other workflows
  workflow_call:
    inputs:
      externalCall:
        description: 'To distinguish workflow_call from other triggers'
        type: boolean
        required: false
        default: true

jobs:

  affected:
    uses: ./.github/workflows/affected.yml
    if: ${{ !inputs.externalCall }}

  build:
    name: Build - ${{ matrix.project }}
    runs-on: ubuntu-latest
    # ignore the error
    if: needs.affected.outputs.affected_projects != '[]'
    needs:
      - affected
    env:
      NX_BASE: ${{ needs.affected.outputs.nx_base }}
      NX_HEAD: ${{ needs.affected.outputs.nx_head }}

    strategy:
      matrix:
        project: ${{ fromJson(needs.affected.outputs.affected_projects) }}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm nx affected -t lint --exclude '*,!${{ matrix.project }}'

      - name: Tests
        run: pnpm nx affected -t test --exclude '*,!${{ matrix.project }}'

      - name: Build
        run: pnpm nx affected -t build --exclude '*,!${{ matrix.project }}' --verbose

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.project }}
          path: dist/
          if-no-files-found: error
