name: CD

on:

  push:
    branches:
      - main
      - 'releases/**'

jobs:

  build:
    uses: ./.github/workflows/build.yml

  deploy-frontend:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
