name: deploy

on:

  push:
    branches:
      - main
      - 'release/**'
      - feat/ci-cd # TODO: remove

jobs:

  affected:
    uses: ./.github/workflows/affected.yml

  build:
    uses: ./.github/workflows/build.yml


  deploy:
    name: Deploy - ${{ matrix.project }}
    needs:
      - affected
      - build
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}

    strategy:
      matrix:
        project: ${{ fromJson(needs.affected.outputs.affected_projects) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/${{ matrix.project }}
          file: ./infra/docker/${{ matrix.project }}.Dockerfile
          push: true
          tags: sgm/${{ matrix.project }}-${{ github.ref_name == 'main' && 'prod'  }}:latest
